"""Person Vault field registry (C / I / E priorities)."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

CATALOG_VERSION = "1.0.0"
AUTH_PROVIDER_NAME = "supabase"

Priority = Literal["C", "I", "E"]
Scope = Literal[
    "universal",
    "education",
    "career",
    "mobility",
    "finance",
    "application",
    "lifestyle",
]
StorageKind = Literal[
    "vault_value",
    "person",
    "educations",
    "work_experiences",
    "projects",
    "skills",
    "certifications",
    "goals",
]
ValueType = Literal["string", "number", "boolean", "date", "json", "array"]


@dataclass(frozen=True, slots=True)
class CatalogField:
    key: str
    section: str
    priority: Priority
    sensitive: bool
    derived: bool
    storage: StorageKind
    applicable_scope: Scope
    value_type: ValueType
    editable: bool
    repeatable: bool
    person_column: str | None = None
    consent_category: str | None = None


def _fields() -> tuple[CatalogField, ...]:
    return (
        # Auth-derived (sparse vault, not editable)
        CatalogField(
            key="auth.user_id",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=False,
            repeatable=False,
        ),
        CatalogField(
            key="auth.email",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=False,
            repeatable=False,
            person_column="email",
        ),
        CatalogField(
            key="auth.email_verified",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="person",
            applicable_scope="universal",
            value_type="boolean",
            editable=False,
            repeatable=False,
            person_column="email_verified",
        ),
        CatalogField(
            key="auth.account_status",
            section="auth",
            priority="C",
            sensitive=False,
            derived=True,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=False,
            repeatable=False,
        ),
        # Person identity (typed on persons table)
        CatalogField(
            key="identity.full_name",
            section="identity",
            priority="C",
            sensitive=False,
            derived=False,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            person_column="full_name",
        ),
        CatalogField(
            key="identity.preferred_name",
            section="identity",
            priority="I",
            sensitive=False,
            derived=False,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            person_column="preferred_name",
        ),
        CatalogField(
            key="identity.phone",
            section="identity",
            priority="I",
            sensitive=False,
            derived=False,
            storage="person",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            person_column="phone",
        ),
        # Sparse preferences
        CatalogField(
            key="preferences.preferred_language",
            section="preferences",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="preferences.communication_style",
            section="preferences",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="preferences.learning_style",
            section="preferences",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        # Typed section presence (completion probes)
        CatalogField(
            key="education.records",
            section="education",
            priority="C",
            sensitive=False,
            derived=True,
            storage="educations",
            applicable_scope="education",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="education.program",
            section="education",
            priority="C",
            sensitive=False,
            derived=False,
            storage="educations",
            applicable_scope="education",
            value_type="json",
            editable=True,
            repeatable=True,
        ),
        CatalogField(
            key="education.gpa",
            section="education",
            priority="C",
            sensitive=False,
            derived=False,
            storage="educations",
            applicable_scope="education",
            value_type="json",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="career.work_history",
            section="career",
            priority="C",
            sensitive=False,
            derived=True,
            storage="work_experiences",
            applicable_scope="career",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="career.projects",
            section="career",
            priority="I",
            sensitive=False,
            derived=True,
            storage="projects",
            applicable_scope="career",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="career.skills",
            section="career",
            priority="C",
            sensitive=False,
            derived=True,
            storage="skills",
            applicable_scope="career",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="career.certifications",
            section="career",
            priority="I",
            sensitive=False,
            derived=True,
            storage="certifications",
            applicable_scope="career",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="application.goals",
            section="application",
            priority="I",
            sensitive=False,
            derived=True,
            storage="goals",
            applicable_scope="application",
            value_type="json",
            editable=False,
            repeatable=True,
        ),
        CatalogField(
            key="application.career_interest",
            section="application",
            priority="I",
            sensitive=False,
            derived=False,
            storage="goals",
            applicable_scope="application",
            value_type="string",
            editable=True,
            repeatable=True,
        ),
        # Mobility / finance / lifestyle sparse
        CatalogField(
            key="mobility.passport_number",
            section="mobility",
            priority="C",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="mobility",
            value_type="string",
            editable=True,
            repeatable=False,
            consent_category="mobility",
        ),
        CatalogField(
            key="mobility.relocation_willingness",
            section="mobility",
            priority="I",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="mobility",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="mobility.preferred_regions",
            section="mobility",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="mobility",
            value_type="array",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="finance.funding_status",
            section="finance",
            priority="I",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="finance",
            value_type="string",
            editable=True,
            repeatable=False,
            consent_category="finance",
        ),
        CatalogField(
            key="finance.scholarship_interest",
            section="finance",
            priority="E",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="finance",
            value_type="boolean",
            editable=True,
            repeatable=False,
            consent_category="finance",
        ),
        CatalogField(
            key="lifestyle.work_life_balance",
            section="lifestyle",
            priority="E",
            sensitive=False,
            derived=False,
            storage="vault_value",
            applicable_scope="lifestyle",
            value_type="string",
            editable=True,
            repeatable=False,
        ),
        CatalogField(
            key="accessibility.accommodation_needs",
            section="accessibility",
            priority="I",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="string",
            editable=True,
            repeatable=False,
            consent_category="accessibility",
        ),
        CatalogField(
            key="demographics.date_of_birth",
            section="demographics",
            priority="E",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="date",
            editable=True,
            repeatable=False,
            consent_category="demographics",
        ),
        CatalogField(
            key="family.sponsor_contact",
            section="family",
            priority="E",
            sensitive=True,
            derived=False,
            storage="vault_value",
            applicable_scope="universal",
            value_type="json",
            editable=True,
            repeatable=False,
            consent_category="family",
        ),
    )


VAULT_CATALOG: dict[str, CatalogField] = {f.key: f for f in _fields()}


def get_catalog_field(key: str) -> CatalogField | None:
    return VAULT_CATALOG.get(key)


def catalog_for_api() -> list[dict]:
    return [
        {
            "key": f.key,
            "section": f.section,
            "priority": f.priority,
            "sensitive": f.sensitive,
            "derived": f.derived,
            "storage": f.storage,
            "applicableScope": f.applicable_scope,
            "valueType": f.value_type,
            "editable": f.editable,
            "repeatable": f.repeatable,
            "consentCategory": f.consent_category,
        }
        for f in _fields()
    ]
